### ISSUE TITLE
CogVLM on MPS

### ISSUE THREAD

**Issue by WillCMcC** [xzhxzhxzhxzhxzh/WebAgent#1]
It looks like you are running on mac! Did you need to do anything special to get it working, other than updating the device to mps? I am encountering issues with this particular line running the model: https://huggingface.co/THUDM/cogagent-chat-hf/blob/d519da3b191401234f4bd86ce1c287c61bc276a3/visual.py#L40 .

**Comment by JonathanReiss15** [comment]
I'm also curious about this :)

**Comment by xzhxzhxzhxzhxzh** [comment]
Hi! The model was running on the server with two 4090 GPUs, I'm sorry I can't help you

**Comment by sudhamjayanthi** [comment]
@JonathanReiss15 @WillCMcC did any of you figure out a solution to run this on mac yet?
